function [fitresult, gof] = createFitNew(mua, mus, Var, TypeFit, title_var)
%CREATEFIT(MUA,MUS,AA)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : mua
%      Y Input : mus
%      Z Output: AA
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 31-Jan-2021 23:23:20


%% Fit: 'untitled fit 1'.
[xData, yData, zData] = prepareSurfaceData( mua, mus, Var );

% Set up fittype and options.
ft = fittype( TypeFit );
opts = fitoptions( 'Method', 'LinearLeastSquares' );
opts.Normalize = 'on';
opts.Robust = 'LAR';

% Fit model to data.
[fitresult, gof] = fit( [xData, yData], zData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, [xData, yData], zData );
legend( h, 'untitled fit 1', 'True', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'mua', 'Interpreter', 'none' );
ylabel( 'mus', 'Interpreter', 'none' );
zlabel( title_var, 'Interpreter', 'none' );
grid on
view( 28.9, 23.9 );


